project:
  type: sdca-theme

website:
  title: "DP-Next"
  # TODO: Change REPO-NAME to the name of the current repo
  site-url: "https://steno-aarhus.github.io/dp-next/"
  repo-url: "https://github.com/steno-aarhus/dp-next"
  navbar:
    pinned: true
    left:
      - index.qmd 
      - text: WP1
        menu:
          - wp1/index.qmd
          - wp1/introduction.qmd
          - wp1/strategy.qmd
          - wp1/planning.qmd
          - wp1/application.qmd
      - wp2.qmd 
      - wp3.qmd 
      - wp4.qmd 
    tools:
      - icon: github
        href: "https://github.com/steno-aarhus/"
      - icon: twitter
        href: "https://twitter.com/StenoAarhusRes"
  sidebar:
      - id: wp1
        title: "WP1"
        style: "floating"
        collapse-level: 2
        contents:
          - wp1/index.qmd
          - wp1/introduction.qmd
          - wp1/strategy.qmd
          - wp1/planning.qmd
          - wp1/application.qmd


format: 
  sdca-theme-html: 
    mermaid-format: svg
bibliography: references.bib
csl: vancouver.csl

editor: 
  markdown:
    wrap: 72
    canonical: true
