project:
  type: sdca-theme

website:
  title: "DP-Next"
  site-url: "https://steno-aarhus.github.io/dp-next/"
  repo-url: "https://github.com/steno-aarhus/dp-next"
  navbar:
    pinned: true
    left:
      - index.qmd 
      - sidebar:wp1
      - text: WP2
        href: wp2.qmd 
      - text: WP3
        href: wp3.qmd 
      - text: WP4
        href: wp4.qmd 
      - text: Who We Are
        href: who-we-are.qmd
    tools:
      - icon: github
        href: "https://github.com/steno-aarhus/"
      - icon: twitter
        href: "https://twitter.com/StenoAarhusRes"
  sidebar:
      - id: wp1
        title: "WP1"
        style: "floating"
        collapse-level: 2
        contents:
          - wp1/index.qmd
          - wp1/introduction.qmd
          - wp1/strategy.qmd
          - wp1/roadmap.qmd
          - wp1/application.qmd

format: 
  sdca-theme-html

bibliography: references.bib
csl: vancouver.csl

editor: 
  markdown:
    wrap: 72
    canonical: true
