---
title: "Who We Are"
---
DP-Next will be carried out by a cross-disciplinary team of epidemiologists, clinicians, health scientists and data scientists across all seven Steno Diabetes Centres:

[Daniel Witte](https://orcid.org/0000-0002-0769-2922) is professor of Diabetes Epidemiology at Aarhus University and has worked across various themes in prevention and prediction of diabetes and its complications in (inter)national cohorts and register-based studies. He will be the Principal Investigator of the DP-Next project. 

[Stine Byberg](https://orcid.org/0000-0002-3626-3609) is an epidemiologist and Senior researcher at Steno Diabetes Center Copenhagen, and currently also Head of Research at Steno Diabetes Center Greenland. Stine has extensive experience in both conducting and supervising students in prediction models using register-based data. Stine will be the work package leader for Work Package 2.

[Claus Bogh Juhl](https://orcid.org/0000-0002-4285-5459) is clinical professor at University Hospital of Southern Denmark, Esbjerg and program leader of Clinical Interventions at Steno Diabetes Center Odense. The has extensive experience in clinical research within type 2 diabetes, obesity and type 1 diabetes. He will be the work package leader for Work Package 3.

[Inger Katrine Dahl-Petersen](https://orcid.org/0000-0002-3157-8847) is a researcher/special consultant at Steno Diabetes Center Copenhagen. She is experienced in co-creating complex interventions and evaluation in the field of GDM and prevention of type 2 diabetes and has substantial experience in coordination of research projects. She will be the work package leader for WP4.

[Gunnar Toft](https://orcid.org/0000-0002-7542-6853) is senior researcher at SDCA, with broad epidemiological experience and experience in coordination of international research projects. He will act as general coordinator of the DP-Next project.

[Karoline Kragelund Nielsen](https://orcid.org/0000-0002-4058-0615) is a senior researcher and heads the reproductive & family health group at Steno Diabetes Center Copenhagen. She has vast experience with research related to GDM, prevention of type 2 diabetes and health systems research, including intervention, epidemiological and qualitative research. She will contribute to the project with her expertise within GDM, epidemiology and intervention research.

[Maria Skaalum Petersen](https://orcid.org/0000-0001-9404-8440), professor in health science, is Head of Research at SDCF together with Dr. Johannesen, endocrinologist. She is also head of the Department of Research at the National Hospital of the Faroe Islands. She has a broad epidemiological experience and experience in conducting research projects in the Faroe Islands. She will contribute to the project with her expertise within epidemiology and registry data in the Faroe Islands. 

