---
title: "Work Package 1"
description: Doing 'better research in less time' by following modern collaboration and planning practices.
---

::: content-hidden
## First round application

644 characters

WP1 answers the increasing need for openness, transparency, and
reproducibility in research, will deliver the day-to-day project and
operations management of all the WPs and will facilitate close
collaboration and joint expertise development across all Steno Centres.

Effective coordination and management of complex projects such as
DP-Next requires modern and innovative approaches to project and
operational management. We will employ tools developed and tested at
SDCA in the past years 6–10 to offer a practical framework for sharing
knowledge and technical skills across centres, aiming to deliver "better
research done in less time" 11.

6.  Johnston, L., Kjærgaard, A. & Sandbæk, A. Grant Proposal: A
    framework for an open and scalable infrastructure for health data
    exemplified by the DD2 initiative. Grant Proposal: A framework for
    an open and scalable infrastructure for health data exemplified by
    the DD2 initiative https://zenodo.org/records/6511112.

7.  Johnston, L., Silverman, O. & Toft, G. Steno Register-based Project:
    Interplay between diabetes and intergenerational transmission of
    health determinants over the life course. Steno Register-based
    Project: Interplay between diabetes and intergenerational
    transmission of health determinants over the life course
    https://steno-aarhus.github.io/darter-project/.

8.  Steno Diabetes Center Aarhus. Internal Documentation on working with
    UK Biobank data. Internal Documentation on working with UK Biobank
    data https://steno-aarhus.github.io/ukbAid/.

9.  Steno Diabetes Center Aarhus. Github Repository for Research at
    Steno Diabetes Center Aarhus. Github Repository for Research at
    Steno Diabetes Center Aarhus https://github.com/steno-aarhus.

10. Beicher, K., Brødbæk, S. & Johnston, L. Seedcase. Seedcase
    https://seedcase-project.org/about/.

11. Lowndes, J. S. S. et al. Our path to better science in less time
    using open data science tools. Nat. Ecol. Evol. 1, 160 (2017).

## Brainstorming

- The way I envision this WP is to take the structured, open, engineering, and
reproducible practices I've been developing and applying to smaller projects and
use it for much larger, multi-center one.

## Second round

- 0 / 1800 characters

:::

## Summary

Science is increasingly moving into more team-based, multi-centered
enterprises, as well as having a greater requirement for openness and
reproducibility. These require using modern practices designed for these
conditions, rarely seen in academia but common within many industry
settings. Our aim with WP1 is to deliver “better, open, and reproducible
research done in less time” by employing these practices, as well as
providing upskilling opportunities to researchers for skills and
knowledge in these practices.

Our basic strategies will be to establish working groups (see Table \##
and Figure \## for more details on these groups), including a group
dedicated to “research operations” to fulfil this core aim, as well as
developing and implementing common practices and tools that maximise
collaboration and that follow some guiding principles (see Table ##).
All groups will include a “tech lead” who has technical knowledge and
skills and who will also be part of the research operations group, to
help coordinate WP groups with these practices. We aim to onboard and
train the tech leads in these practices by embedding them in some work
done at SDCA, where these practices have been developing and refining
over the last several years. The most relevant practices and skills that
this WP1 aims to provide are in software and data engineering, iterative
project management, collaborative workflows and tools,

Pertinent to these practices is understanding and assessing risk and
challenges. The two biggest challenges we face with this WP1 are 1) the
need for highly technical personnel who have sufficient fundamental
expertise to understand and apply these practices, and 2) the IT systems
across centers that often don’t work well together. For the first
challenge, we hope to minimise it through the training and onboarding of
the tech leads. For the second challenge, we hope that having a
dedicated research operations group will reduce the impact it might have
on this project.

While this WP1 forms the foundation to all other WPs and in many ways
aims to support their success, the activities of WP1 are an increasingly
needed aspect of research globally. In this regard, we aim to produce
tangible and usable deliverables that are independent and valuable on
their own (see Table \## for the list of tasks, milestones, and
deliverables).

## Overall

```{mermaid}
%%| file: images/gantt.mmd
%%| label: fig-gantt
%%| fig-cap: "General Gantt chart for all of DP-Next."
```

## WP specific

```{mermaid}
%%| file: images/gantt-wp1.mmd
%%| label: fig-gantt-wp1 
%%| fig-cap: "Gantt chart for Work Package 1"
```

## Introduction

We’ve structured and organised this Work Package 1 based on the
increasing need for openness, transparency, and reproducibility in
research. WP1 will deliver the day-to-day project and operations
management of all the WPs and will facilitate the close collaboration
and joint development of expertise across all seven Steno Centers.
Effective coordination and management of complex projects such as this
project requires modern and innovative approaches to project and
operational management. We will employ resources and tools developed and
tested at SDCA in the past years
(https://doi.org/10.5281/zenodo.6511112,
https://github.com/steno-aarhus/, https://seedcase-project.org,
https://steno-aarhus.github.io/darter-project/,
https://steno-aarhus.github.io/ukbAid/) to offer a practical framework
for sharing knowledge and technical skills across centres, aiming to
deliver “better research done in less time”
(https://doi.org/10.1038/s41559-017-0160).

::: {.callout-important icon=false appearance="minimal"}
### Visions

*Doing better research in less time*

*Training researchers in modern technical engineering and project management skills*

*Establish modern data engineering practices and research operational approaches as a standard of practice when conducting research*
:::

::: {.callout-important icon=false appearance="minimal"}
### Aims

- Create management groups to manage and coordinate centers and WPs in
completing their deliverables. 

- Develop and implement cross-Steno
Research Operations and modern collaborative workflows and practices
that support the successful completion of each work package as well as
improving research practices across Steno centers. 

- Optimise and reduce
the time and effort spent between designing the work package studies and
the final disseminating high-quality research results. 

- Build up inter-
and intra-Steno knowledge and skill capacity ("upskill") in
non-traditional technical skills and knowledge such as software
development, data engineering, operational management (including
"DataOps"), and iterative project management practices.
:::

## Strategy

Traditional management of larger scale research projects often involves
setting up steering committees who check on progress through status
updates and discuss solutions to issues that arise. However, there are
many modern tools and methods used within industry that research
environments and projects could benefit from, such as data engineering,
software development, and operations management. Thus, our general
strategy incorporates not only the standard project management
activities as well as modern approaches to coordinating tasks and
outputs between groups. The general strategies we’ll take are to:

Establish an overall management group and a research operations group of
relevant persons from each center to track progress, coordinate tasks,
and manage the project Develop and agree on some guiding principles for
collaboration and work to follow across centers and WPs that adhere to
open science practices Investigate and identify resources, limitations,
and barriers on cross-Steno collaboration practices and processes
Develop and agree on a set of common tools and standards to use across
centers for WP to have smoother collaboration and sharing of outputs,
that also consider the barriers and resources as well as the guiding
principles

### Guiding principles

One of the steps in the strategy involves developing and implementing
general principles that will guide collaboration and work across the
Steno Centers. This ensures we have a basis for following a common
approach to working and communicating together when managing the WPs.
While we will finalise and refine the principles during the course of
the project, below are some principles that will form the basis for all
other principles.

- Assume openness with as many things as possible, including communication
- Implement openness as much as possible, excluding personal and sensitive data
- Disseminate as many steps of the research lifecycle as possible, including non-traditional outputs (e.g. protocols or standard operating procedures)
- Implement as much as possible explicit analyses and data processing/management using code-based and programmatic pipeline/workflow management

## Practicalities



### Working Groups

The project will be led by the PI, with support from the co-applicants /
Work Package leaders, who together form the management group. Aside from
individual groups for each WP, there will also be a group dedicated to
overseeing the research operations. This group will, at a minimum, be
composed of at least one person from each WP (and preferably in each
center) who acts as a “tech lead” for that WP group. The tech lead
should be someone with above average literacy in
programming/computing/IT.

### Research operations

The aim of research operations is to optimise day-to-day work in order
to minimise time and effort spent per unit of output. The research ops
group will act as a unit that works to reduce tech barriers, develop
software and data engineering processes and tools, and advise on how to
best design the outputs of WPs that are the inputs of other WPs. Some of
the initial tasks revolve around establishing: a communications channel
for everyone (as well as sub-channels for individual WPs and groups)
that make it easy to keep everyone updated and to view all
communications done (not emails); a project management platform visible
and usable by everyone; an effective project management approach that
groups can use to track tasks and deliverables (e.g. a suitable approach
might be using Kanban principles); and a document sharing platform,
ensuring that all of these also follow the guiding principles. Later
tasks include developing the deliverables of the WPs in a way that makes
sharing and interoperability easier, both internal to the project groups
and WPs as well as to external stakeholders.

### Potential tools

- GitHub to use as the knowledge repository
-  Slack/Teams/Discord for communication

## Considerations

### Challenges

Aside from the standard project management tasks, implementing modern
research ops and collaborative practices that support conducting open
and reproducible science across all Steno Centers will be a challenge.
Given that personnel in research environments with the necessary
technical knowledge and skills are few and often move out of academia
into industry positions, a substantial amount of time and effort will be
spent in training and upskilling existing personnel. The reason we’ve
structured the groups to include at least one “tech lead” who is also
part of the research ops group is to help minimise this challenge. We
aim to provide training to this tech lead by embedding them in some of
the work we are doing at Steno Aarhus, where we have been implementing
many of these practices.

Another major challenge will be coordinating tasks and work between IT
systems that often don’t work well together or are suboptimally designed
for cross-institution collaboration. This is one reason we’ve decided to
establish a research ops group, so that we can minimise the impact these
issues have on completing the project deliverables.

## Outputs

### Milestones

-   Setup research data infrastructure that supports adhering to open
    FAIR practices for ease of internal and external sharing of data for
    WP3 (using software built from NNF-funded project from SDCA called
    Seedcase: https://seedcase-project.org/)

-   Open-source templates for building software package/app for risk
    prediction engine from WP2

### Deliverables

-   Report: *Consensus document on agreed upon processes and workflows
    between WPs*
-   Report: *Research operational management practices and processes
    employed in a large-scale multi-centered project: Future uses of
    using modern approaches to team-based research*
-   Report: *DP-Next as an open-access and secure Data Resource for
    broader re-use of collected data for researchers* (using
    SDCA-developed, NNF-funded Seedcase software)
-   Report: *Challenges and lessons learned in applying modern research
    ops and data engineering to a large-scale, multi-center project*
-   Resource: Each center has resources