---
title: "Work Package 3: Heterogeneity"
---

WP3 will characterise heterogeneity among people in early middle age with HbA1c defined pre-diabetes. The aim is to identify a set of easily obtainable biomarkers that can optimally distinguish those with high probability of stable pre-diabetes/remission from those at highest risk of progression to diabetes.
## WP 3.1 Risk clustering and long-term prediction
WP3.1 will investigate to which degree detailed biological data (e.g. genetics, omics, health behavioural data) can improve risk prediction within a Danish ([ADDITION-PRO](https://bmcpublichealth.biomedcentral.com/articles/10.1186/1471-2458-12-1078)) and a Greenlandic ([Greenland Health Surveys](https://www.tandfonline.com/doi/full/10.1080/22423982.2019.1709257)) context. Both cohorts recruited participants more than a decade ago and examined a wide set of cardiometabolic and genetic risk factors, health behaviours and biomarkers, including fat distribution measures and physical activity measures from week long combined heart rate/accelerometer readings. We will link these cohorts to the register-based risk predictions from WP2 (backdated to each cohort baseline), and examine the added predictive value of individual biological risk indicators and of risk factor clusters. The availability of more than a decade of accrued follow-up for diabetes incidence in these cohorts will enable us to obtain a global indication of diabetes risk clusters within the first year of DP-Next.

## WP 3.2 Deep Phenotyping of HbA1c defined pre-diabetes
### Hypothesis: Among individuals with routinely identified prediabetes based on HbA1c, deep phenotyping with non-invasive methods will identify subgroups at the highest risk of progression to T2D and subgroups likely to maintain prediabetes or achieve remission; beyond the predictive ability of age, sex, HbA1c and BMI.

### Background: 
Although elevated blood glucose precedes T2D onset by over a decade14, many people with slightly elevated HbA1c do not progress to diabetes15. Depending on the criteria for prediabetes, 10-40% develop T2D within 1-5 years16–18 and 17-45% revert to normoglycaemia15, pointing to significant heterogeneity in diabetes risk among individuals with prediabetes19–21. A relatively recent cluster-driven diabetes subclassification delineated two subgroups with relatively young age of diabetes onset and absence of marked obesity and low insulin secretion22, which map to genetic, metabolic and phenotypic characteristics already present in pre-diabetes. Notably, a recent study identified elevated liver fat and diminished beta-cell function as the most predictive factors for progressing to T2D in people with pre-diabetes23, highlighting the need to extend precision approaches for diabetes prevention beyond genetic predisposition and insulin resistance. 
The current vision for precision prevention integrates data from genetic, biological (multi-omic), health behavioural and psycho-social components; however, few cohorts have these data in a contemporary population defined in a clinical context.

### Strategic Vision:
WP3 establishes such a cohort across Steno Centers with long-term academic and strategic visions. The strategic vision is to establish the facilities, expertise and capacity across all Steno Centers to carry out multi-center clinical studies with a standardised protocol and management/data infrastructure. We also want to prepare the centers for the standardised application of deep phenotyping close to clinical practice by applying a high degree of standardisation, openness and reproducibility ([WP1](https://steno-aarhus.github.io/dp-next/wp1/)).

### Academic Objectives:
Academically, we describe a core protocol, which will be carried out within the DP-Next budget and timeframe, and an extended protocol, which describes our ambitions for deeper phenotyping and longer follow-up. Funding for the extended protocol will be sought separately on a project basis and will build on the capacity established in the core protocol. Connection and coordination will be sought with new Danish phenotyping initiatives currently underway or in the planning process (e.g. PRECiSE).

### Who will be included:
In the core protocol we will identify a cohort of 1000 individuals aged 40 to 55 years who have recently (within the past 12 months) had a routine HbA1c measurement in the pre-diabetic range (42-47 mmol/mol) and are not using any glucose lowering medication. This age range was chosen to maximise life-long impact on diabetes risk. Sample size calculations use our recent analysis of HbA1c defined (pre)diabetes in Denmark1, showing that 25 to 40% of Danish residents aged 40-55 had at least 1 HbA1c measurement in 2018. In our target age range pre-diabetes incidence was 9/1000 person years, and the subsequent incidence of diabetes was 7/1000, and hence an expected cumulative T2D incidence of 22% in a median of 3.5 years of follow-up. Logistic regression based power calculations show that a cohort of 1050 individuals gives us 0.9 power at a 0.05 significance level to detect an odds ratio of at least 1.28 per standard deviation in a continuous exposure variable.

### Recruitment:
Participants will be recruited in Odense (350), Aarhus (350), Aalborg (150), Greenland (50) and the Faroe Islands (50). We intend to include 100 individuals of Greenlandic ancestry, 50 living in Denmark and 50 living in Greenland. Participants will be recruited based on data from routine HbA1c checks, accessed through the LABKA registers. Consequently the clinical decisions prompting a HbA1c measurement will form part of the selection process, reflecting current clinical practice.

### Core Protocol:
Participants will be invited to answer an online questionnaire (medical and family history, sociodemographic data, health literacy, food habits and cravings , personality traits such as willingness to take risks, quality of life, self-perceived mental stress, depression, anxiety, sleep apnea scores) followed by a 4-hour clinical examination at one of the Steno Diabetes Centers. The programme includes: anthropometric measures (height, weight, waist-hip ratio, and DEXA-scan for body composition), a 5-point oral glucose tolerance test to estimate insulin sensitivity and beta-cell function, liver elastography to estimate liver fat and liver stiffness, blood pressure, heart rate variability and pulse-wave velocity for arterial stiffness estimation. Participants will measure physical activity with a combined heart rate monitor / accelerometer during 7 days following the visit. Blood samples will be analysed for lipids and HbA1c and processed for biobanking of plasma, serum and DNA. The biobank will further include urine, saliva and faeces samples. All further measurements will be in biobank samples as part of the extended protocol.

The primary outcome for the core protocol is incident Type 2 Diabetes. The LABKA register will identify incident T2D (based on routine HbA1c) supplemented with a study HbA1c measurement at the end of the DP-Next project. The primary statistical analysis will use unsupervised Latent Class Analysis28 to map the heterogeneity across all measured variables. LCA will be carried out at two levels: a full model including all available data and a minimal model using as few data as possible with limited loss of strength. Modelling studies show that our sample of 1000 is sufficient to identify patterns and clusters in most data sets.

### Extended Protocol:
Our ambition is to extend the WP3 protocol beyond the budget and time of DP-Next. Additional funding will be sought to expand the depth of the cardiometabolic phenotyping under real life settings, including a 24-hour ambulatory blood pressure, cardiorespiratory monitoring, and continuous glucose monitoring, with simultaneous app-based diet diaries. We further have the ambition to invite a subset of ~300 participants for a second examination with optical coherence tomography to detect early retinal changes, a single breath-hold MR scan of the liver, and an OGTT during short-term oral steroid treatment. We intend to expand the project carrying out a comprehensive set of omics analyses in biobank materials, including genotyping, proteomics, metabolomics and metagenomic characterisation of faeces and saliva as well as a set of targeted biomarkers covering mechanisms such as endothelial function, liver function and auto-immunity (GAD and islet cell antibodies). Our ambition is to extend the follow-up beyond the DP-Next project period, extending the accrual not only of diabetes cases but also of secondary endpoints such as cardiovascular events.
