%%{init: {
  'theme': 'neutral', 
  'gantt': {
    'barHeight': 25,
    'leftPadding': 125
  }
}}%%
gantt
    title Estimated timeline and activities for DP-Next project
    dateFormat  YYYY-MM-DD
    axisFormat %Y
    tickInterval 1year
    todayMarker off
    %% (`excludes` accepts specific dates in YYYY-MM-DD format, days of the week ("sunday") or "weekends", but not the word "weekdays".)

    section WP1<br>Management<br>and Collaboration
    T1.1 General project management: t1_1, 2025-01-01, 5y
    T1.2 Optimising collaboration: t1_2, 2025-01-01, 5y

    section WP2<br>Risk Prediction
    T2.1 Separate model development: t2_1, 2025-01-01, 18M
    T2.2 Machine Learning approaches: t2_2, 2026-01-01, 18M
    T2.3 Joint model development: t2_3, 2026-07-01, 18M
    T2.4 Validation: t2_4, 2028-01-01, 18M

    section WP3<br>Heterogeneity
    T3.1 Advanced clustering models: t3_1, 2027-07-01, 18M
    T3.2 Deep phenotyping substudy: t3_2, 2025-07-01, 54M

    section WP4<br>Development<br>and intervention
    T4.1 Investigate barriers and facilitators: t4_1, 2025-01-01, 18M
    T4.2 Develop & co-design: t4_2, after t4_1, 18M
    T4.3 Pilot test in specific populations: t4_3, after t4_2, 1y
    T4.4 Evaluation: t4_4, 2028-07-01, 18M
