---
title: "Abstract"
description: "Doing 'better research in less time' by following modern collaboration, open, and planning practices."
---

Science, while generating cutting-edge knowledge, lags behind most
industry settings when it comes to practical, operational aspects. For
instance, while much of research done now relies heavily on software and
computational work, funding agencies rarely fund software and data
engineering projects, nor do many research groups hire these highly
skilled technical personnel. So, the aim of Work Package 1 is to
establish these skills and needs as a core component of this project and
to help do "better research in less time".

Our basic strategies will be to establish working groups, including a
group dedicated to "research operations" to fulfil this core aim, as
well as developing and implementing common practices and tools that
maximise collaboration and that follow some guiding principles. All
groups will include a "tech lead" who has technical knowledge and skills
and who will also be part of the research operations group, to help
coordinate WP groups with these practices. We aim to onboard and train
the tech leads in these practices by embedding them in some work done at
SDCA, where these practices have been developing and refining over the
last several years. The most relevant practices and skills that this WP1
aims to provide are in software and data engineering, iterative project
management, collaborative workflows and tools,

Pertinent to these practices is understanding and assessing risk and
challenges. The two biggest challenges we face with this WP1 are:

1.  The need for highly technical personnel who have sufficient
    fundamental expertise to understand and apply these practices, which
    we hope to minimise through the training and onboarding of the tech
    leads.
2.  the IT systems across centers that often don’t work well together,
    which we hope to reduce the impact of by having a dedicated research
    operations group.

While this WP1 forms the foundation to all other WPs and in many ways
aims to support their success, the activities of WP1 are an increasingly
needed aspect of research globally. In this regard, we aim to produce
tangible and usable deliverables that are independent and valuable on
their own.
