---
title: "Introduction"
description: Background and motivation for project as well as its visions and aims.
---

Science is state of the art in seeking and gaining knowledge, and yet it
lags far behind in general operational, organisational, and
technological aspects when compared to industry settings. For instance,
there are nearly no research software engineers within research groups
or institutions, even though software is a foundational component to
conducting research in the modern era.

Likewise, basic modern communication and project management tools are
rarely, if ever, used within research environments, even though they are
standard practice in many corporate settings. If these things are used
by some groups, they are not shared nor advertised through traditional
scientific publications, so if they exist, others can't reuse and learn
from each other to improve how we do research.

Science is also increasingly moving into more team-based, multi-centered
enterprises, as well as having a greater requirement for openness and
reproducibility. These require using modern practices designed for these
conditions, rarely seen in academia but common within many industry
settings.

Our aim with WP1 is to deliver "better, open, and reproducible research
done in less time" by employing these practices, as well as providing
upskilling opportunities to researchers for skills and knowledge in
these practices.

We’ve structured and organised Work Package 1 (WP1) based on the
increasing need for openness, transparency, and reproducibility in
research. WP1 will deliver the day-to-day project and operations
management of all the WPs, as well as facilitating the close
collaboration and joint development of expertise across all seven Steno
Centers. 

To achieve effective and optimal coordination and management of
a complex project like this, we will apply modern and innovative methods
in project and operational management practices, as well as applying a
software and data engineering structure and perspective both operational
aspects as well as to scientific outputs. We will employ resources and
tools developed and tested at SDCA in the past years [@Johnston2022;
@DARTER; @ukbaid; @seedcase; @sdca-github] to offer a practical
framework for sharing knowledge and technical skills across centres,
which will deliver "better research done in less time" [@Lowndes2017]
while following reproducible and open scientific practices.

## Visions

-   *Better research done in less time*

-   *Researchers with modern technical engineering-based and project
    management skills embedded in more groups*

-   *Modern data engineering practices and research operational
    approaches established as a standard of practice when conducting
    research*

## Aims

-   Create management groups to manage and coordinate centers and WPs in
    completing their deliverables.

-   Develop and implement cross-Steno Research Operations and modern
    collaborative workflows and practices that support the successful
    completion of each work package as well as improving research
    practices across Steno centers.

-   Optimise and reduce the time and effort spent between designing the
    work package studies and the final disseminating high-quality
    research results.

-   Build up inter- and intra-Steno knowledge and skill capacity
    ("upskill") in non-traditional technical skills and knowledge such
    as software development, data engineering, operational management
    (including "DataOps"), and iterative project management practices.

## References
