---
title: "Roadmap"
description: General project planning, outputs, and Gantt charts for WP1.
---

This document covers the basic, overall plan for DP-Next as well as the
plan for WP1. While the Gantt charts display an overview of the project,
the sections below on milestones and deliverables provide more detailed
information than what can be put on the charts.

```{mermaid}
%%| file: images/gantt.mmd
%%| label: fig-gantt
%%| fig-cap: "Gantt chart showing high-level tasks and deliverables for all WPs within DP-Next."
```

```{mermaid}
%%| file: images/gantt-wp1.mmd
%%| label: fig-gantt-wp1 
%%| fig-cap: "Gantt chart showing some basic tasks, milestones, and deliverables for Work Package 1"
```

## Milestones

-   Setup project website to host details and documents relevant to this
    project and it's WPs

-   Setup website to document and describe research operational
    practices used across Centers for easier sharing and onboarding

-   Open-source template Data Management Plan to use for WP3

-   Setup research data infrastructure that supports adhering to open
    FAIR practices for ease of internal and external sharing of data for
    WP3 (using software built from NNF-funded project from SDCA called
    Seedcase: https://seedcase-project.org/)

-   Open-source templates for building software package/app for risk
    prediction engine from WP2

## Deliverables

::: {layout-ncol="2"}
### Reports

-   Consensus document on agreed upon processes and workflows between
    WPs
-   Research operational management practices and processes employed in
    a large-scale multi-centered project: Future uses of using modern
    approaches to team-based research
-   DP-Next as an open-access and secure Data Resource for broader
    re-use of collected data for researchers (using SDCA-developed,
    NNF-funded Seedcase software)
-   Challenges and lessons learned in applying modern research ops and
    data engineering to a large-scale, multi-center project

### Resources

-   Each center has resources and workflows for conducting reproducible
    and modern register-based research using the Danish registers
-   DP-Next data resource
-   DP-Next project website, with all (internal and external) knowledge
    generated, including all code and documentation
:::
